spring:
  application:
    name: greeting-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
greeting-service:
  greeting: "Eae"
  default-value: "Mermão"



